services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PUBLIC_POSTHOG_URL=${PUBLIC_POSTHOG_URL:-https://eu.i.posthog.com}
      - PUBLIC_POSTHOG_TOKEN=${PUBLIC_POSTHOG_TOKEN:-phc_KBLc1ExggN021vOnZvXf5Ech2Bauk1jwZrrdJuBKUOU}
      - SQLITE_DB_PATH=/data/cogisoft.db
      - TG_CHAT_ID=${TG_CHAT_ID}
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
    volumes:
      - ./data:/data
