services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4321:4321
    environment:
      - PUBLIC_POSTHOG_URL=${PUBLIC_POSTHOG_URL:-https://eu.i.posthog.com}
      - PUBLIC_POSTHOG_TOKEN=${PUBLIC_POSTHOG_TOKEN:-pub}
      - SQLITE_DB_PATH=/data/cogisoft.db
    env_file:
      - .env
    volumes:
      - ./data:/data
